-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxxKAulZMZugJAfQw
s29Ca2IdMAuxoXFdfjOY3Twqrm6gCgYIKoZIzj0DAQehRANCAAT/LvRaUGzDmbIg
L+sagJHHvPLCIU3Uxunh3lQ476sbaydyKHgrS7iQrP/gpfx7tCuWWCG4qWovYxk4
CCbbu7J1
-----END PRIVATE KEY-----